### ISSUE TITLE
Certificate verification error ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by iesiyok** [WICG/webpackage#473] opened 2019-07-29 12:17 UTC
Hi there,

I am doing the same instructions here https://github.com/WICG/webpackage/tree/master/go/signedexchange without the trusted signed exhanges.

```
>echo "<h1>hi</h1>" > payload.html
>openssl ecparam -out priv.key -name prime256v1 -genkey
>openssl req -new -sha256 -key priv.key -out cert.csr -subj '/CN=localhost/O=Test/C=US'
>openssl x509 -req -days 360 -in cert.csr -signkey priv.key -out cert.pem \
  -extfile <(echo -e "1.3.6.1.4.1.11129.2.1.22 = ASN1:NULL\nsubjectAltName=DNS:localhost")
>gen-certurl -pem cert.pem -ocsp <(echo ocsp) > cert.cbor
>gen-signedexchange \
  -uri https://localhost:1447/welcome/hello.html \
  -content ./payload.html \
  -certificate cert.pem \
  -privateKey priv.key \
  -certUrl https://issuer.org.dev:1448/cert.cbor \
  -validityUrl https://localhost:1447/resource.validity.msg \
  -o payload.sxg
```

I am using nginx:
>vim nginx.conf
```
server {
      listen 1448 ssl;
      server_name issuer.org.dev;
       ssl_certificate      cert_ca/sites/issuer/dev.issuer.org.crt;
       ssl_certificate_key  cert_ca/sites/issuer/dev.issuer.org.key;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       ssl_prefer_server_ciphers  on;
       ssl_ciphers  ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;
       ssl_dhparam cert/dhparam.pem;
       ssl_session_cache   shared:SSL:40m; #40M size of cache
       ssl_session_timeout 2h; #2 hours
       ssl_session_tickets on;
      root /usr/local/etc/openresty/cert_ca/sites/webserver/v2;
      location /cert.cbor {
       
      }

      location /payload.sxg {

        add_header Cache-Control "no-transform";
        add_header X-Content-Type-Options "nosniff";

      }
    }

```

>curl -k -i https://issuer.org.dev:1448/payload.sxg           
```
HTTP/1.1 200 OK
Server: openresty/1.15.8.1
Date: Mon, 29 Jul 2019 12:09:39 GMT
Content-Type: application/signed-exchange;v=b3
Content-Length: 570
Last-Modified: Mon, 29 Jul 2019 11:55:26 GMT
Connection: keep-alive
ETag: "5d3edeae-23a"
Cache-Control: no-transform
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

>curl -k -i https://issuer.org.dev:1448/cert.cbor  
```
HTTP/1.1 200 OK
Server: openresty/1.15.8.1
Date: Mon, 29 Jul 2019 12:10:34 GMT
Content-Type: application/cert-chain+cbor
Content-Length: 419
Last-Modified: Mon, 29 Jul 2019 11:54:48 GMT
Connection: keep-alive
ETag: "5d3ede88-1a3"
Accept-Ranges: bytes
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

```
>vim a.html
<html>
<head>
	<link rel="prefetch" href="https://issuer.org.dev:1448/payload.sxg" >
</head>
<body>
</body>
</html>
```

>`google-chrome a.html --args --user_data_dir=/dev/null Support/Google/Chrome/Default --ignore-certificate-errors-spki-list=`openssl x509 -noout -pubkey -in cert.pem | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | base64` --enable-features=SignedHTTPExchange`

>The page is empty and inspect gives two errors like the following:

**Certificate verification error: ERR_CERT_AUTHORITY_INVALID
Failed to load resource: net::ERR_INVALID_SIGNED_EXCHANGE**

What could I do to solve this?

**Comment by irori** [comment] 2019-07-30 08:28
ERR_CERT_AUTHORITY_INVALID error suggests that `--ignore-certificate-errors-spki-list` flag is not working as intended.

When you launched `google-chrome`, did you see an infobar saying "You are using unsupported command-line flag: --ignore-certificate-errors-spki-list=<base64 value>. Stability and security will suffer." ? If not, try again after closing all other Google Chrome windows.

**Comment by iesiyok** [comment] 2019-07-30 09:24
Thank you very much for your support.

I exactly see the infobar saying "You are using unsupported command-line flag: --ignore-certificate-errors-spki-list=. Stability and security will suffer."

I couldn't find anything about this problem,

**Comment by irori** [comment] 2019-07-30 09:51
Just to confirm, the infobar showed some base64 encoded string after `--ignore-certificate-errors-spki-list=`, right?

If not, just run
```
openssl x509 -noout -pubkey -in cert.pem | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | base64
```
and see what happens.

**Comment by iesiyok** [comment] 2019-07-30 10:31
No, it shows the base64 

You are using unsupported command-line flag: --ignore-certificate-errors-spki-list=Elmufwo55170Htld8S5/7ffozDOe9khQzoxDqfltY2I=.  Stability and security will suffer.

**Comment by twifkak** [comment] 2019-07-30 15:35
I wonder if the problem is `--user_data_dir=/dev/null`; try putting an empty directory there.

**Comment by twifkak** [comment] 2019-07-30 15:36
Oh, that should be `user-data-dir` with dashes not underscores.

**Comment by iesiyok** [comment] 2019-07-30 15:41
I think it works now, but I couldn't figure out how to use this with link prefetch.
Imagine I just have a json file packed with sxg.
In html header I prefetch it, 
<link rel="prefetch" href="https://issuer.org.dev:1448/payload.sxg" >

in body, I want to use it if its signature is verified.

$.get( "https://issuer.org.dev:1448/payload.sxg", function( data ) {
  console.log( data );
});

But it gives me the raw .sxg content:
sxg1-b3!https://localhost:1447/hello.htmlW�label;cert-sha256=*HrdZMVAqYm+rynoFP3GM89JfKxwqfbTbSPAXG7ysMrU=*;cert-url="https://issuer.org.dev:1448/cert.cbor";date=1564498201;expires=1564501801;integrity="digest/mi-sha256-03";sig=*MEUCIQD/FQBZ9rBybf0c4u0BTK8rheTOgkkjtWmy1xqqkcunYAIgS3GMVx7wJ/5Sn/536+R3GQnslM92SqtCZNfyThwM3oE=*;validity-url="https://localhost:1447/resource.validity.msg"�FdigestX9mi-sha256-03=KJEdU9urAJP74QIDJW9z7/ehLlmaZmbRdlYb73Nu/3k=G:statusC200Lcontent-typeXtext/html; charset=utf-8Pcontent-encodingLmi-sha256-03{
 ...............

I want to get the json content, are there any events that I can check if the signature verified and I can take the content without the signature and so on?

**Comment by irori** [comment] 2019-07-31 05:22
In Chrome, currently signed exchanges cannot be used as XHR targets. It can be used only as main resources, for example:

```
<head>
<link rel="prefetch" href="https://issuer.org.dev:1448/payload.sxg" >
</head>
<a href="https://issuer.org.dev:1448/payload.sxg">navigate to SXG</a>
```

This prefetches a sxg, and if a user clicks the link, navigates to the sxg content (using the prefetched sxg resource).

**Comment by irori** [comment] 2019-08-02 08:54
Closing, but feel free to add comments if you have further questions.

**Closed by irori** 2019-08-02 08:54 UTC
