### ISSUE TITLE
gen-bundle is broken for HAR files

### ISSUE THREAD

**Issue by myrzakereyms** [WICG/webpackage#663] opened 2021-08-17 04:41 UTC
Currently, when creating a web bundle using the gen-bundle Go tool and a .har file, trying to navigate to this bundle returns ERR_INVALID_WEB_BUNDLE.
To reproduce:
1. Get the gen-bundle tool.
2. Navigate to https://web.dev/web-bundles/
3. Save all as HAR with content
4. Create a web bundle with a command: gen-bundle -har $PATH_TO_HAR -o webdev.wbn -primaryURL https://web.dev/web-bundles/
5. Navigate to it with a web bundle flag turned on.
6. Instead of seeing the https://web.dev/web-bundles/ page, get an error ERR_INVALID_WEB_BUNDLE.

**Comment by horo-t** [comment] 2021-08-17 05:15
I can create a web bundle file, and successfully loaded the web bundle in Chrome.

Could you please check that the HAR file contains the content of each response. If not, please make sure that open the DevTools before navigating to the page https://web.dev/web-bundles/. I think the resources which are received before DevTools is open may not be included in the HAR file.

**Comment by irori** [comment] 2021-08-17 05:19
@myrzakereyms gave me a HAR file he used to reproduce this issue.

The problem was that in the HAR (and in the .wbn created from it) the response for `https://web.dev/web-bundles/` had status code 304 (Not modified). Chrome rejects non-200 responses (https://crbug.com/990733), resulting in the ERR_INVALID_WEB_BUNDLE error.

- As a workaround, check "Disable cache" in the DevTools network tab when creating a HAR file.
- 304 responses in HAR generated by Chrome have response body. Maybe `gen-bundle` can just replace 304 status code to 200.

**Comment by horo-t** [comment] 2021-08-17 06:29
I see.
Making `gen-bundle` change 304 status code to 200 sounds reasonable to me.

**Comment by myrzakereyms** [comment] 2021-08-17 07:00
I see. This makes way more sense than the tool randomly breaking. As the change is very small, I will include it in the "add b2 version" PR and then close this issue.

**Comment by hayatoito** [comment] 2021-08-17 07:25
I chatted with @myrzakereyms. Our conclusion is:
- A bundler tool doesn't have to be too *smart*.  A bundler doesn't have to change 304 status code to 200 implicitly.
- There are many useful tools which manipulates JSON better than a bundler does, such as `jq`. Users can  replace 304 with 200 with `jq` easily, and then pass it to a bundler.

So I'd suggest to close this issue as WONTFIX, if we can agree on that.

**Comment by irori** [comment] 2021-08-17 08:20
If we don't "fix" this, we should update the [instructions](https://github.com/WICG/webpackage/tree/main/go/bundle#from-a-har-file) in README.md to make sure that "Disable cache" is checked when creating a HAR file.

**Comment by hayatoito** [comment] 2021-08-17 09:30
> If we don't "fix" this, we should update the instructions in README.md to make sure that "Disable cache" is checked when creating a HAR file.

Thanks! SGTM. What we want to update is the instructions, instead of a bundler itself, I think.

**Comment by hayatoito** [comment] 2021-08-18 06:21
@myrzakereyms Could you have a chance to update the instruction in a separate PR?

**Closed** 2021-08-19 05:41 UTC
